#spring:
#
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    driverClassName: org.postgresql.Driver
#    hibernate:
#      ddl-auto: update
#
#  datasource:
#    url: jdbc:postgresql://localhost:5432/yourDatabaseName
#    username: postgres
#    password:

spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/maintenance_project_db?useSSL=false&Timezone=true&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true