#spring:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:

#spring.datasource.url: jdbc:mysql://localhost:3306/maintenance_project_db
#spring.datasource.username: root
#spring.datasource.password:

#spring.jpa.hibernate.ddl-auto: update
#spring.datasource.url: jdbc:mysql://localhost:3306/maintenance_project_db?useTimezone=true&serverTimezone=UTC&SSL=false
#spring.datasource.username: root
#spring.datasource.password:

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    h2:
      console:
        enabled: true