#server:
#  port: 8080
#
#spring:
#  profiles:
#    active: dev

server:
  port: 8080

spring:
  application:
    name: MaintenanceProjectApplication

  profiles:
    active: prod

  output:
    ansi:
      enabled: ALWAYS